kind: Deployment
apiVersion: apps/v1
metadata:
  name: ms-rrts-at-elastic
  namespace: production
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ms-rrts-at-elastic
  strategy:
    type: Recreate
  minReadySeconds: 10
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600
  template:
    metadata:
      labels:
        app: ms-rrts-at-elastic
    spec:
      initContainers:
      - name: busybox
        image: busybox
        imagePullPolicy: Always
        command: ['sh', '-c', "chown -R 1000:1000 /usr/share/elasticsearch/data"]
        volumeMounts:
        - name: elasticsearch-local-storage
          mountPath: /usr/share/elasticsearch/data
      containers:
        - name: ms-rrts-at-elastic
          image: docker.elastic.co/elasticsearch/elasticsearch:8.13.2
          imagePullPolicy: Always
          resources:
            limits:
              cpu: 1500m
              memory: 2Gi
            requests:
              cpu: 250m
              memory: 2Gi
          env:
            - name: discovery.type
              value: single-node
            - name: ES_JAVA_OPTS
              value: '-Xmx1g -Xms1g'
            - name: bootstrap.memory_lock
              value: 'true'
            - name: xpack.security.enabled
              value: 'true'
            - name: xpack.security.http.ssl.enabled
              value: 'false'
            - name: xpack.security.transport.ssl.enabled
              value: 'false'
            - name: xpack.security.authc.api_key.enabled
              value: 'true'
            - name: xpack.monitoring.collection.enabled
              value: 'true'
            - name: xpack.security.enrollment.enabled
              value: 'true'
            - name: xpack.security.authc.token.enabled
              value: 'true'
            - name: ELASTIC_PASSWORD
              value: 'ms_admin'
          ports:
          - name: elastic-port
            containerPort: 9200
          volumeMounts:
            - name: elasticsearch-local-storage
              mountPath: /usr/share/elasticsearch/data
              subPath: data
      volumes:
      - name: elasticsearch-local-storage
        persistentVolumeClaim:
          claimName: elasticsearch-pvc